#ifndef __CONTROL_CTX
#define __CONTROL_CTX

#define PB_CONTROL_CLICK_SHORT 0x01
#define PB_CONTROL_CLICK_LONG  0x02
#define PB_CONTROL_CLICK       0x03
#define PB_CONTROL_PUSH_LONG   0x04


#endif //__CONTROL_CTX